### ISSUE TITLE
Add a wrapper for matADi materials

### ISSUE THREAD

**Issue by adtzlr** [adtzlr/felupe#128]
MatADi materials always operate with variables and results in lists whereas FElupe takes unpacked inputs and returns an array or a tuple of arrays as output.

A wrapper should be added as

```python
nh = matadi.MaterialHyperelastic(matadi.models.neo_hooke, C10=0.5, bulk=5000)

umat = MatADiMaterial(nh)
umat.gradient(F)
```

This is necessary to use a matadi material as `umat` of `newtonrhapson` - currently an error is raised. In user codes this is of course no problem because the user knows how to interact with a matADi material by its README.

# Tasks
- [ ] create a wrapper function
- [ ] add it to init and felupe namespace
- [ ] add a test without importing MatADi (?)

**Comment by adtzlr** [comment]
The wrapper should be created in `constitution._wrappers.MatadiMaterial
