### ISSUE TITLE
Isolate the submodules

### ISSUE THREAD

**Issue by adtzlr** [adtzlr/felupe#822]
The submodules are not well isolated, i.e. the imports from one submodule are done through non-public imports of another module. It could be a good idea to isolate all submodules as stand-alone modules. This enables well-defined (public) API's between the submodules. If the codebase of one submodule gets bigger and bigger, it may easily be outsourced as a standalone package.

Example: With the current imports, the `assembly` module can't be imported, see attempt #821.

### Submodule Import Checks
- [x] `assembly` has to be added to the global imports, see #826.
- [x] `constitution` needs some minimal changes, see #826.
- [x] `dof` is okay.
- [x] `element` is okay.
- [x] `field` needs some minimal changes, see #826.
- [x] `math` is okay.
- [x] `mechanics` needs a change in `from ..tools._misc`, see #825.
- [x] `mesh` depends on `tools._plot.ViewMesh`. This file should be moved to a new submodule, like `view`, see #823.
- [x] `quadrature` needs a change in `from ..element._lagrange import ...`, see #824.
- [x] `region` is okay.
- [x] `solve` is okay.
- [x] `tools` is fine, except for the version string `from ..__about__ import __version__` instead of `from .. import __version__` (won't be fixed now).
